"""
JDFTx runner — generate input files, run, parse output.
For Phase 2 validation: solvation + electrode potential.
"""

import logging
import subprocess
from pathlib import Path
from typing import Optional

import numpy as np
from ase import Atoms

logger = logging.getLogger("engine.runners.jdftx")


def she_to_mu(V_she: float, V_ref: float = 4.44) -> float:
    """Convert electrode potential vs SHE (Volts) to JDFTx target-mu (Hartrees)."""
    return -(V_ref + V_she) / 27.2114


class JDFTxRunner:
    """Generate, run, and parse JDFTx calculations for solvated systems."""

    def __init__(
        self,
        jdftx_path: str = "jdftx",
        pseudopotential_dir: str = "GBRV",
        n_cores: int = 16,
        settings: dict = None,
    ):
        self.jdftx_path = jdftx_path
        self.pseudo_dir = pseudopotential_dir
        self.n_cores = n_cores
        self.settings = settings or {}
        self._check_available()

    def _check_available(self):
        """Check if JDFTx binary is accessible."""
        try:
            result = subprocess.run(
                [self.jdftx_path, "--help"],
                capture_output=True, timeout=5
            )
            self.available = True
            logger.info(f"JDFTx found: {self.jdftx_path}")
        except (FileNotFoundError, subprocess.TimeoutExpired):
            self.available = False
            logger.warning(f"JDFTx not found at '{self.jdftx_path}'. Using mock mode.")

    @property
    def is_available(self) -> bool:
        return self.available

    def generate_input(
        self,
        atoms: Atoms,
        output_prefix: str = "calc",
        solvation: dict = None,
        potential_vs_SHE: float = None,
        cutoff_Ry: int = 20,
    ) -> str:
        """
        Generate JDFTx input file content.

        Parameters:
            atoms: ASE Atoms object (slab + shell)
            output_prefix: Prefix for output files
            solvation: {"solvent": "H2O", "cation": "K+ 1.0", "anion": "OH- 1.0"}
            potential_vs_SHE: Electrode potential (V vs SHE), or None for neutral
            cutoff_Ry: Plane-wave cutoff (Rydberg)

        Returns:
            String content of .in file
        """
        cell = atoms.cell
        positions = atoms.positions
        symbols = atoms.get_chemical_symbols()

        lines = []
        lines.append(f"# JDFTx input — generated by fuel-cell-engine")
        lines.append(f"# System: {len(atoms)} atoms")
        lines.append("")

        # Lattice (convert Å to Bohr: 1 Å = 1.8897 Bohr)
        bohr = 1.8897259886
        lines.append("lattice \\")
        for i in range(3):
            row = cell[i] * bohr
            lines.append(f"    {row[0]:.6f}  {row[1]:.6f}  {row[2]:.6f}" +
                        (" \\" if i < 2 else ""))
        lines.append("")

        # Ion species
        unique_elements = sorted(set(symbols))
        for elem in unique_elements:
            lines.append(f"ion-species {self.pseudo_dir}/$ID_pbe.uspp")
        lines.append("")

        # Cutoff
        lines.append(f"elec-cutoff {cutoff_Ry} {cutoff_Ry * 4}")
        lines.append("elec-ex-corr gga-PBE")
        lines.append("")

        # Coulomb interaction (slab geometry)
        lines.append("coulomb-interaction Slab 001")
        lines.append("")

        # Atomic coordinates (cartesian, Bohr)
        lines.append("coords-type cartesian")
        for i, (sym, pos) in enumerate(zip(symbols, positions)):
            pos_bohr = pos * bohr
            # 1 = movable, 0 = fixed
            movable = 1
            tags = atoms.get_tags()
            if i < len(tags) and tags[i] == 0:
                movable = 0
            lines.append(
                f"ion {sym}  {pos_bohr[0]:.6f}  {pos_bohr[1]:.6f}  "
                f"{pos_bohr[2]:.6f}  {movable}"
            )
        lines.append("")

        # Solvation
        if solvation:
            lines.append("fluid LinearPCM")
            lines.append(f"pcm-variant {self.settings.get('pcm_variant', 'CANDLE')}")
            lines.append(f"fluid-solvent {solvation.get('solvent', 'H2O')}")
            if "cation" in solvation:
                lines.append(f"fluid-cation {solvation['cation']}")
            if "anion" in solvation:
                lines.append(f"fluid-anion {solvation['anion']}")
            lines.append("")

        # Electrode potential (grand canonical)
        if potential_vs_SHE is not None:
            mu = she_to_mu(potential_vs_SHE)
            lines.append("elec-smearing Fermi 0.001")
            lines.append(f"target-mu {mu:.6f}")
            lines.append("")

        # Optimization
        lines.append("ionic-minimize nIterations 50")
        lines.append("")

        # Output
        lines.append(f"dump-name {output_prefix}.$VAR")
        lines.append("dump End State Forces BoundCharge")

        return "\n".join(lines)

    def run(
        self,
        input_content: str,
        work_dir: str,
        job_name: str = "jdftx_calc",
    ) -> Optional[dict]:
        """
        Write input file and run JDFTx.

        Parameters:
            input_content: Generated input file string
            work_dir: Directory for input/output files
            job_name: Name prefix

        Returns:
            {"energy": float (eV), "converged": bool, "output_path": str}
            or None on failure.
        """
        if not self.is_available:
            return self._mock_run(input_content, work_dir)

        work_path = Path(work_dir)
        work_path.mkdir(parents=True, exist_ok=True)

        input_path = work_path / f"{job_name}.in"
        output_path = work_path / f"{job_name}.out"

        # Write input
        input_path.write_text(input_content, encoding="utf-8")

        # Run
        cmd = f"mpirun -np {self.n_cores} {self.jdftx_path} -i {input_path} -o {output_path}"
        logger.info(f"Running JDFTx: {cmd}")

        try:
            result = subprocess.run(
                cmd, shell=True, capture_output=True, text=True,
                timeout=3600 * 12,  # 12 hour max
            )

            if result.returncode != 0:
                logger.error(f"JDFTx failed: {result.stderr[:500]}")
                return None

            # Parse output
            return self.parse_output(str(output_path))

        except subprocess.TimeoutExpired:
            logger.error("JDFTx timed out (12h)")
            return None
        except Exception as e:
            logger.error(f"JDFTx run error: {e}")
            return None

    def parse_output(self, output_path: str) -> Optional[dict]:
        """
        Parse JDFTx output file for energy and convergence.

        Returns:
            {"energy_eV": float, "energy_Ha": float, "converged": bool}
        """
        Ha_to_eV = 27.2114

        try:
            content = Path(output_path).read_text(encoding="utf-8")

            # Find final energy (last "Etot" line)
            energy_Ha = None
            converged = False

            for line in content.split("\n"):
                if "Etot" in line and "=" in line:
                    try:
                        energy_Ha = float(line.split("=")[-1].strip().split()[0])
                    except (ValueError, IndexError):
                        pass
                if "IonicMinimize: Converged" in line:
                    converged = True

            if energy_Ha is None:
                logger.error(f"Could not parse energy from {output_path}")
                return None

            return {
                "energy_Ha": float(energy_Ha),
                "energy_eV": float(energy_Ha * Ha_to_eV),
                "converged": converged,
                "output_path": output_path,
            }

        except FileNotFoundError:
            logger.error(f"Output file not found: {output_path}")
            return None

    # --- Mock ---

    def _mock_run(self, input_content: str, work_dir: str) -> dict:
        """Mock JDFTx run — return realistic energy."""
        # Count atoms from input
        n_atoms = input_content.count("\nion ")
        energy_Ha = -5.0 * n_atoms + np.random.normal(0, 0.01)

        return {
            "energy_Ha": energy_Ha,
            "energy_eV": energy_Ha * 27.2114,
            "converged": True,
            "output_path": f"{work_dir}/mock.out",
        }
