"""
Reporter — generate output files: CSV, markdown, plots.
"""

import logging
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

logger = logging.getLogger("engine.utils.reporter")


def generate_results_csv(results, output_path: str, synterra_query=None):
    """Save all candidate results to CSV, with recipe availability."""
    rows = []
    for c in results.candidates:
        row = {
            "iteration": c.iteration,
            "status": c.status,
            "elapsed_s": c.elapsed_s,
            **c.params,
            **c.scores,
            "failure_reason": c.failure_reason,
        }
        # Add uncertainty
        for k, v in c.uncertainty.items():
            row[f"unc_{k}"] = v

        # Add recipe availability
        if synterra_query and c.status == "success":
            recipe_results = synterra_query.search_by_elements(
                _params_to_elements(c.params), max_results=1
            )
            row["recipe_available"] = len(recipe_results) > 0
            row["synthesis_feasibility"] = "MEDIUM" if recipe_results else "LOW"
        else:
            row["recipe_available"] = False
            row["synthesis_feasibility"] = "UNKNOWN"

        rows.append(row)

    df = pd.DataFrame(rows)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)
    logger.info(f"Results CSV saved: {output_path} ({len(df)} rows)")
    return df


def generate_ranked_md(results, output_path: str, synterra_query=None, top_n: int = 10):
    """Generate ranked candidates markdown report with recipes."""
    successful = [c for c in results.candidates if c.status == "success"]
    successful.sort(key=lambda c: sum(c.scores.values()), reverse=True)
    top = successful[:top_n]

    lines = [
        "# Ranked Candidates",
        f"Date: generated by engine",
        f"Total evaluated: {len(results.candidates)}",
        f"Successful: {len(successful)}",
        f"Failed: {results.n_failed}",
        "",
        "⚠️ **RANKING ONLY** — absolute numbers ±0.15 eV uncertainty.",
        "⚠️ **LIMITATION:** This pipeline predicts ACTIVITY and STABILITY (thermodynamic).",
        "   It CANNOT predict DURABILITY (kinetic degradation). Durability MUST be tested in lab.",
        "",
        "## Top Candidates",
        "",
        "| Rank | Config | HOR | H₂ barrier | O₂ barrier | Stability | Score | Recipe? | Feasibility |",
        "|------|--------|-----|-----------|-----------|-----------|-------|---------|-------------|",
    ]

    for i, c in enumerate(top, 1):
        config_str = _params_short(c.params)
        hor = c.scores.get("hor_activity", 0)
        h2 = c.scores.get("h2_barrier", 0)
        o2 = c.scores.get("o2_barrier", 0)
        stab = c.scores.get("shell_stability", 0)
        score = sum(c.scores.values())

        # Recipe lookup
        has_recipe = "❌"
        feasibility = "LOW"
        if synterra_query:
            elements = _params_to_elements(c.params)
            recipes = synterra_query.search_by_elements(elements, max_results=1)
            if recipes:
                has_recipe = "✅"
                feasibility = "MEDIUM"

        lines.append(
            f"| {i} | {config_str} | {hor:.3f} | {h2:.3f} | {o2:.3f} | "
            f"{stab:.3f} | {score:.3f} | {has_recipe} | {feasibility} |"
        )

    # Detailed recipe section for top candidates
    if synterra_query:
        lines.extend(["", "## Synthesis Recipes (from SynTERRA)", ""])
        for i, c in enumerate(top[:5], 1):
            elements = _params_to_elements(c.params)
            recipes = synterra_query.search_by_elements(elements, max_results=2)
            config_str = _params_short(c.params)

            lines.append(f"### Candidate {i}: {config_str}")
            if recipes:
                for r in recipes:
                    lines.append(f"- {r['recipe_summary']}")
                lines.append("")
                lines.append(
                    "  ⚠️ BULK solid-state recipe. For nanoparticle/thin-film: "
                    "adapt approach (co-reduction, sputtering, MOF pyrolysis)."
                )
            else:
                lines.append("- No recipe found in SynTERRA. Custom synthesis required.")
            lines.append("")

    lines.extend([
        "",
        "## Insights",
        "",
        _generate_insights(successful),
        "",
        "## Backup Candidates (If Top 3 Fail in Lab)",
        "",
    ])

    # 6.5: Backup candidates (rank 4-10)
    backup = successful[3:10] if len(successful) > 3 else []
    if backup:
        lines.append("| Rank | Config | Score | Note |")
        lines.append("|------|--------|-------|------|")
        for i, c in enumerate(backup, 4):
            config_str = _params_short(c.params)
            score = sum(c.scores.values())
            lines.append(f"| {i} | {config_str} | {score:.3f} | Backup — avoid re-running engine |")
        lines.append("")
        lines.append("*If top 3 fail in lab, try these BEFORE re-running compute pipeline.*")
    else:
        lines.append("- Not enough candidates for backup list.")

    lines.extend([
        "",
        "## Constraints Check",
        "",
    ])

    n_pass_constraints = sum(1 for c in successful
                            if c.failure_reason != "constraint_violation")
    lines.append(f"- Passed all constraints: {n_pass_constraints}/{len(successful)}")

    # 6.6: Durability limitation documentation
    lines.extend([
        "",
        "---",
        "",
        "## ⚠️ CRITICAL LIMITATIONS",
        "",
        "### Durability CANNOT Be Predicted",
        "",
        "This pipeline predicts **ACTIVITY** (thermodynamic: will the reaction happen?)",
        "and **STABILITY** (thermodynamic: will the structure survive?).",
        "",
        "It **CANNOT** predict **DURABILITY** (kinetic: how long before degradation?).",
        "",
        "Durability depends on:",
        "- Membrane/ionomer degradation (chemical, not predictable by MACE/OC20)",
        "- Carbon corrosion over time",
        "- Catalyst dissolution/migration",
        "- Water management failures",
        "- Impurity poisoning",
        "",
        "**Action required:** Allocate ≥50% of lab budget for durability testing,",
        "not just initial activity measurement.",
        "",
        "### Vacuum ≠ Reality",
        "",
        "All ML predictions (OC20, MACE, CHGNet) are computed in **vacuum**.",
        "Real operation is in **KOH 7M electrolyte at 70°C with applied potential**.",
        "",
        "JDFTx Phase 2 partially bridges this gap, but is still an approximation.",
        "Only lab experiments provide ground truth.",
        "",
        "### Numbers Are Approximate",
        "",
        "⚠️ Absolute numbers (eV values) have ±0.15 eV uncertainty.",
        "Trust the **RANKING** (A > B > C), not the exact values.",
        "",
    ])

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    logger.info(f"Ranked MD saved: {output_path}")


def generate_pareto_plot(results, output_path: str):
    """Generate Pareto front plot (HOR activity vs shell stability)."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        logger.warning("matplotlib not available, skipping plot")
        return

    successful = [c for c in results.candidates if c.status == "success"]
    if not successful:
        return

    hor = [c.scores.get("hor_activity", 0) for c in successful]
    stab = [c.scores.get("shell_stability", 0) for c in successful]

    fig, ax = plt.subplots(1, 1, figsize=(8, 6))
    ax.scatter(hor, stab, c="steelblue", alpha=0.7, edgecolors="k", linewidth=0.5)

    # Highlight top 3
    sorted_by_score = sorted(successful, key=lambda c: sum(c.scores.values()), reverse=True)
    for i, c in enumerate(sorted_by_score[:3]):
        x = c.scores.get("hor_activity", 0)
        y = c.scores.get("shell_stability", 0)
        ax.scatter([x], [y], c="red", s=100, zorder=5, marker="*")
        ax.annotate(f"#{i+1}", (x, y), textcoords="offset points", xytext=(5, 5))

    ax.set_xlabel("HOR Activity (closer to 0 = better)")
    ax.set_ylabel("Shell Stability (higher = better)")
    ax.set_title("Pareto Front: Activity vs Stability")
    ax.axvline(x=0, color="gray", linestyle="--", alpha=0.3, label="Pt reference (ΔG=0)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    logger.info(f"Pareto plot saved: {output_path}")


def generate_calibration_report(cal_report, output_path: str):
    """Save calibration report to markdown."""
    content = cal_report.summary()
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    logger.info(f"Calibration report saved: {output_path}")


def generate_verification_report(ver_report, output_path: str):
    """Save verification report to markdown."""
    content = ver_report.summary()
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    logger.info(f"Verification report saved: {output_path}")


def generate_all_reports(results, calibration, verification, config, synterra_query=None):
    """Generate all output files."""
    output_dir = config.output.dir
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    generate_results_csv(results, f"{output_dir}/{config.output.results_csv}", synterra_query)
    generate_ranked_md(results, f"{output_dir}/{config.output.ranked_md}", synterra_query)
    generate_pareto_plot(results, f"{output_dir}/{config.output.pareto_plot}")

    if calibration:
        generate_calibration_report(calibration, f"{output_dir}/{config.output.calibration_report}")

    if verification:
        generate_verification_report(verification, f"{output_dir}/{config.output.verification_report}")


def _params_short(params: dict) -> str:
    """Short config string."""
    parts = []
    dopant = params.get("dopant_type", "none")
    if dopant != "none":
        parts.append(f"{dopant}{int(params.get('dopant_percent', 0))}")
    else:
        parts.append("Ni")
    parts.append(f"{int(params.get('n_layers', 2))}L")
    parts.append(f"{int(params.get('vacancy_percent', 0))}%v")
    if params.get("n_doping_percent", 0) > 0:
        parts.append(f"{int(params['n_doping_percent'])}%N")
    return " ".join(parts)


def _params_to_elements(params: dict) -> list[str]:
    """Extract element list from candidate params."""
    elements = ["Ni"]
    dopant = params.get("dopant_type", "none")
    if dopant and dopant != "none":
        elements.append(str(dopant))
    return elements


def _generate_insights(successful: list) -> str:
    """Auto-generate insights from results."""
    insights = []

    # Best dopant
    by_dopant = {}
    for c in successful:
        d = c.params.get("dopant_type", "none")
        score = sum(c.scores.values())
        by_dopant.setdefault(d, []).append(score)

    if by_dopant:
        best_dopant = max(by_dopant, key=lambda k: np.mean(by_dopant[k]))
        insights.append(f"- **Best dopant:** {best_dopant} (avg score {np.mean(by_dopant[best_dopant]):.3f})")

    # Best layers
    by_layers = {}
    for c in successful:
        l = int(c.params.get("n_layers", 2))
        score = sum(c.scores.values())
        by_layers.setdefault(l, []).append(score)

    if by_layers:
        best_layers = max(by_layers, key=lambda k: np.mean(by_layers[k]))
        insights.append(f"- **Best shell layers:** {best_layers} (avg score {np.mean(by_layers[best_layers]):.3f})")

    return "\n".join(insights) if insights else "- Insufficient data for insights"
